language: objective-c


env:
 matrix:
  - MONO_VERSION="3.2.6"


before_install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

 
script:
  - xbuild KeyGeneratingCaches.sln /property:Configuration=Release
  - nunit-console ./KeyGeneratingCaches.UnitTests/bin/Release/KeyGeneratingCaches.UnitTests.dll -exclude Excluded
